23.DjangoCSV/FormToCSV/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('form_to_csv.urls'))
]

23.DjangoCSV/form_to_csv/urls.py
from django.urls import path
from form_to_csv import views
urlpatterns = [
    path('', views.home_view, name='home_view'),
    path('download_csv/', views.download_csv, name='download_csv'),
    path('add_data/', views.add_data, name='add_data'),
    path('wipe_database', views.wipe_database, name='wipe_database')
    
]

23.DjangoCSV/form_to_csv/models.py
from django.db import models
import datetime
# Create your models here.
class CSVStore(models.Model):
    user_name = models.CharField(max_length=200)
    user_text = models.CharField(max_length=1000)
    time = models.DateTimeField(auto_now_add=True)

23.DjangoCSV/form_to_csv/forms.py
from django import forms
from django.db.models import fields 
from .models import CSVStore
# creating a form  
class InputForm(forms.ModelForm):
    class Meta:
        model = CSVStore
        fields = ['user_name', 'user_text']
        

23.DjangoCSV/form_to_csv/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .forms import InputForm
from .models import CSVStore
import csv
# Create your views here.
def home_view(request):
    context = {}
    return render(request, 'form_to_csv/index_page.html', context)
    
def download_csv(request):
    query_set = CSVStore.objects.all()
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="data.csv"'
    writer = csv.writer(response)
    writer.writerow(['username', 'message', 'message_time'])
    for item in query_set:
        writer.writerow([item.user_name, item.user_text, item.time.strftime('%m/%d/%Y')])
    return response
    

def add_data(request):
    if request.method == 'GET':
        context = {}
        context['form'] = InputForm()
        return render(request, 'form_to_csv/add_data.html', context)
    elif request.method == 'POST':
        context = {}
        form = InputForm(request.POST)
        if form.is_valid(): form.save()
        else: return HttpResponse('Error in form',status=400)
        context['saved_data'] = request.POST
        return render(request, 'form_to_csv/response.html', context)
    
def wipe_database(request):
    CSVStore.objects.all().delete()
    return HttpResponse('All Objects have been deleted. <a href="/">Back<a>')

23.DjangoCSV/form_to_csv/templates/form_to_csv/add_data.html
{% extends "form_to_csv/layout.html" %} {% block content%}
<h1 class="title">Form to CSV</h1>

<div class="content">
	<p>Enter text to be saved in the below boxes.</p>
</div>

<form class="form" action="" method="post">
	{% csrf_token %} 
	<div class="field">
	<label class="label" for="id_user_name">User Name: </label>
	<input class="input is-primary" type="text" name="user_name" maxlength="200" required="" id="id_user_name">
	<label class="label" for="id_user_text">Message: </label>
	<input class="input is-info" type="text" name="user_text" maxlength="1000" required="" id="id_user_text">
	</div>
	<input type="submit" class="button is-primary is-light" value="Submit" />
</form>
<br />
{%endblock%}

23.DjangoCSV/form_to_csv/templates/form_to_csv/index_page.html
{% extends "form_to_csv/layout.html" %} {% block content%}
<h1 class="title">Form to CSV</h1>
<br />
<br />
<div id='viewport'>
    <p class='content'>Choose action from below.</p>

<p>
<table class="table">
    <tbody>
        <tr>
            <td>
                <p>
                    <a href="/add_data/" class="button is-primary is-light">Add Data </a>
                </p>
            </td>
            <td>
                <p>
                    <a href="/download_csv/" class="button is-link is-light">Download Data</a>
                </p>
            </td>
        </tr>
		<tr><td><button class="button is-white">DANGER:</button></td><td><a class="button is-danger is-light" href="/wipe_database">Wipe DB</a></td></tr>
    </tbody>
</table>
</p>
</div>

{%endblock%}

23.DjangoCSV/form_to_csv/templates/form_to_csv/layout.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<!-- Required meta tags -->
		<meta charset="utf-8" />
		<meta
			name="viewport"
			content="width=device-width, initial-scale=1, shrink-to-fit=no"
		/>

		<!-- Bulma CSS -->
		<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bulma@0.9.1/css/bulma.min.css">
		<!-- My own CSS -->
		<link rel="stylesheet" href="{% static 'css/form_to_csv.css' %}" />

		<title>DjangoCSV</title>
	</head>
	<body>
		{%block content%} This is testing block for Django Templates {%endblock%}

	</body>
</html>

23.DjangoCSV/form_to_csv/templates/form_to_csv/response.html
{% extends "form_to_csv/layout.html"%} {% block content%}
<h1 class="title">Form to CSV</h1>
<div class="notification is-primary is-sucess">
    Response Saved Sucessfully.
    
</div>
<div class="field has-addons"><p class="control"><a class="button is-primary is-light" href="/add_data/">Add more</a></p><p class="control"><a class="button is-info is-light" href="/">Go Back</a></p></div>
{% endblock content%}